### PR TITLE
Add Generic Tracer Sponges

### PR DESCRIPTION
**Pull request by theresa-cordero**
**Overview**
This PR adds a routine to generic tracers  that will initialize the pointers for ALE sponges to be used with any of the generic tracers. 

These sponges are primarily targeted at correcting biases near open boundaries that result from surious mixing from larger issues with the open boundary forcings. However, then could also be used to nudge the interior of the domain to prevent drift over a long simulation as is done with temperature and salinity in the hindecasts used to initalize forecasts from a realistic state. 

**Information for Nudging**
For each variable that is nudged, you will need to add information including: a file with the data, the variable name of the data in that file, and the vertical coordinate of the data. A damping file which sets the timescale of the nudging used by all the generic tracer variables is also needed - it can be the same as the dampling file for T and S. Data for nudging multiple generic tracer variables can be in the same file, or seperate files can be used for each variable.

Here is an example of the setting to nudge no3 and o2:
```
DO_SPONGE_GENERIC_TRACER = True
SPONGE_GT_DAMPING_FILE = "damping.nc"
DO_SPONGE_GT_no3 = True
SPONGE_GT_no3_FILE = "nudging_daily_1990.nc"
SPONGE_GT_no3_VAR = "no3"
SPONGE_GT_no3_ETA_VAR = "Z"
DO_SPONGE_GT_o2 = True
SPONGE_GT_o2_FILE = "nudging_daily_1990.nc"
SPONGE_GT_o2_VAR = "no3"
SPONGE_GT_o2_ETA_VAR = "Z"
```
In the MOM_parameter_doc.all file, if `DO_SPONGE_GENERIC_TRACER = True` then there will be parameters for `DO_SPONGE_GT_$VAR` for each generic tracer used in the simulation. The additional `SPONGE_GT_$VAR_FILE`, `SPONGE_GT_$VAR_VAR`, and `SPONGE_GT_$VAR_ETA_VAR` will only be included if `DO_SPONGE_GT_$VAR=True`.

**Impacts** 
This PR was tested with a configuration and data files provided by Zihua Liu. Thank you! This configuration is ideal for this testing because it is a subset of a larger simulation, so there is a "correct" value for the generic tracers that does not include any boundary artifacts. For this experiment, no3 was nuged in the 10 grid cells nearest the boundaries to the "correct" value. 

The figure below shows monthly average of the surface no3 after 10 monhts of the simultaion in (A) the original run with no nudging, (B) the run with nudging, and (C) the difference (B) minus (A). The high values of no3 near the eastern boundary are the result of vertical mixing and are what the sponges aim to correct. Note that the correction extends well beyond the 10-gird cell nudging region. 

The target concentration of no3 from the parent run are shown in (D) and the difference between the with-nudging and  no-nudging runs are shown in (D) and (F) respectively. Note that the color bar for (C) is an order of mangitude smaller than the color range for (E) and (F).   

image

### CODE REVIEW

**Comment by theresa-cordero** [comment]
@nikizadehgfdl I would appreciate if you could take a look at this if you have time.

**Comment by yichengt900** [comment]
Also, include @gabyneg here. @gabyneg, I think you are also testing the new generic tracer sponge option, right? It would be nice if you could share your results here when they are available, so we can have a better sense of how this new sponge option works.

**Comment by theresa-cordero** [comment]
yes, I am looking forward to adding @gabyneg 's results here!

**Comment by yichengt900** [comment]
Hi @theresa-morrison, when you have a moment, would you mind updating the feature branch to reflect some of the recent code changes (specifically the generic tracer interface update)? This will allow a few users to continue testing the BGC boundary nudging option. Thanks.

**Comment by yichengt900** [comment]
PR https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/MOM6/pull/20 is merged. Close this one now.

**Pull request closed without merging**
